version: "3.8"

services:
  order-db:
    image: postgres:latest
    container_name: order-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=order-db
    ports:
      - "5434:5432"

  order:
    image: dnrmth/ordermanagement-order:latest
    container_name: ordermanagement-order
    environment:
      - DB_URL=jdbc:postgresql://order-db:5432/order-db
      - DB_USER=user
      - DB_PASSWORD=password
    ports:
      - "8081:8089"